
name: ci

on:
  push:
    branches: 
    - 'main'

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix: 
        app: [ web, api ]
    uses: andersondario/templates-central/.github/workflows/main-general.yaml@main
    with:
      app_name: ${{ matrix.app }}
      tags: andersondario/${{ matrix.app }}:${GITHUB_SHA::7}
      context: "{{defaultContext}}:${{ matrix.app }}"