
name: ci

on:
  push:
    branches: 
    - 'main'

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix: 
        app: [ web, api ]
    uses: andersondario/templates-central/.github/workflows/main-general.yaml@main
    with:
      app_name: ${{ matrix.app }}
      repo: andersondario/${{ matrix.app }}
      context: "{{defaultContext}}:${{ matrix.app }}"
    secrets:
      repo_username: ${{ secrets.DOCKERHUB_USERNAME }}
      repo_token: ${{ secrets.DOCKERHUB_TOKEN }}