
name: ci

on:
  push:
    branches: 
    - 'main'

jobs:
  env_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Env
        run: |
          echo "BUILD_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
  ci:
    strategy:
      fail-fast: true
      matrix: 
        app: [ web, api ]
    uses: andersondario/templates-central/.github/workflows/main-general.yaml@main
    with:
      app_name: ${{ matrix.app }}
      tag: andersondario/${{ matrix.app }}:$BUILD_SHA
      context: "{{defaultContext}}:${{ matrix.app }}"
    secrets:
      repo_username: ${{ secrets.DOCKERHUB_USERNAME }}
      repo_token: ${{ secrets.DOCKERHUB_TOKEN }}