
name: pullrequest

on:
  pull_request:
    branches: 
    - 'main'

jobs:
  Test:
    strategy:
      fail-fast: true
      matrix: 
        app: [ web, api ]
    uses: andersondario/templates-central/.github/workflows/pr-nodejs.yaml@main
    with:
      app_name: ${{ matrix.app }}