
name: pullrequest

on:
  pull_request:
    branches: 
    - 'main'

jobs:
  Api-Test:
    name: Api App Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          cd api
          npm ci
          npm run test
      - name: Docker validation
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'
          lint: 'api/hadolint'
  Web-Test:
    name: Web App Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          cd web
          npm ci
          npm run test
      - name: Docker validation
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'web/Dockerfile'
          lint: 'hadolint'